exports.adultVisitKeys = JSON.parse(`{
    "Previous Visit Date": "",
    "Initial Visit Date": {
        "type":"direct",
        "field":"InitialVisitDate"
    },
    "Correct": {
        "type":"direct",
        "value": true
    },
    "Visit Date": {
        "type":"direct",
        "field":"VisitDate"
    },
    "Visit Time": "----",
    "Visit Time Start": {
        "type":"direct",
        "field":"StartTime"
    },
    "Visit Time End": {
        "type":"direct",
        "field":"EndTime"
    },
    "Visit Duration": {
        "type":"input-map",
        "function":"timeDuration",
        "args": [{"field":"StartTime"},{"field":"EndTime"}]
    },
    "Client Level": "ClientLevel",
    "ClientPoints - CO": "----",
    "ClientPoints - TR": "----",
    "Client Score": "ClientScore",
    "Client Type": "ClientType",
    "Funding Level": "",
    "Sub Funding Level - Other": "****",
    "Client Referral Source": "ReferredBy",
    "Previous Client": "PreviousClient",
    "Children's Division": "",
    "DOB": "DateOfBirth",
    "Age": "AgeYears",
    "Marital Status": "MaritalStatus",
    "Street Address": "",
    "Address Line 1": "Address",
    "Address Line 2": "",
    "Address Line 3": "----",
    "City": "City",
    "State": "State",
    "Zip Code": "Zip",
    "Phone Numbers": {
        "type":"question-array",
        "inputs": [
            {
                "Phone Number Type": {"value":"Home"},
                "Phone Number": {"field":"HomePhone"}
            }, 
            {
                "Phone Number Type": {"value":"Work"},
                "Phone Number": {"field":"WorkPhone"}
            }, 
            {
                "Phone Number Type": {"value":"Other"},
                "Phone Number": {"field":"OtherPhone"}
            }
        ]
    },
    "County": "County",
    "Other Specify": "",
    "Lives Alone": "",
    "Who Else": "",
    "Who Else Input - Other": "",
    "Gender Identity": "Gender",
    "Other ": "",
    "Preferred Pronoun": "",
    "Primary Language": "",
    "Speaks/Writes English (Spanish)": "",
    "Specify Primary Lang.": "",
    "Speaks/Writes English (Other)": "",
    "BMI - QG": "----",
    "Height": "",
    "Height (ft)": "",
    "Height (In)": "",
    "Weight": "",
    "Current Weight": "CurrentWeight",
    "Previous Weight": "",
    "Weight Change": "",
    "No Weight Given": "",
    "New BMI - QG": "",
    "New BMI": "BMI",
    "Race": "Race",
    "MultipleRaces": "",
    "Other Race (Multi)": "",
    "Other Race (Single)": "",
    "Employment Status": "EmploymentStatus",
    "Retired": "",
    "Disabled": "",
    "FT Stay-At-Home Parent": "",
    "Relationship to Child": "RelationshipToChild",
    "Specify Relationship": "",
    "Income": "FamilyYearlyIncome",
    "Previous Income": "",
    "Household Members": "",
    "Type of Aid": "",
    "Type of Aid - Specify": "",
    "Emergency Contact Name": "----",
    "EC First Name": "EmergencyContactName",
    "EC Last Name": "",
    "EC Relationship": "EmergencyContactRelationship",
    "EC Phone Numbers": {
        "type":"question-array",
        "inputs": [
            {
                "inp1":"*Home",
                "inp2":"EmergencyContactHomePhone"
            }, 
            {
                "inp1":"*Work",
                "inp2":"EmergencyContactWorkPhone"
            }, 
            {
                "inp1":"*Other",
                "inp2":"EmergencyContactOtherPhone"
            }
        ]
    },
    "Initial Default EC Phone Number Type": "----",
    "Initial Default EC Phone Number": "----",
    "Parenting Partner": {
        "type":"conditional",
        "if":"ParentingPartnerName",
        "then":"Yes",
        "else":"No"
    },
    "Parenting Partner Name": "----",
    "PP First Name": "ParentingPartnerName",
    "PP Last Name": "",
    "PP Relationship": "ParentingPartnerRelationship",
    "PP Employment Status": "",
    "PP Retired": "",
    "PP Disabled": "",
    "PP Schooling Status": "",
    "PP Current Schooling Level": "",
    "PP Specify Other Schooling": "",
    "PP FT Stay-At-Home Parent": "",
    "Insurance": "Insurance",
    "Medicaid Number": "MedicaidNumber",
    "Status": {
        "if":"MedicaidPending",
        "then":"Pending",
        "else":""
    },
    "Other Insurance": "",
    "Other Insurance Status": "",
    "Medical Provider Name": "",
    "Medical Provider First Name": "DoctorsFirstName",
    "Medical Provider Last Name": "DoctorsLastName",
    "Medical Visits Primary": "",
    "PMP Appointment Date": "",
    "Appointment Scheduled": "",
    "Primary Appointment Kept": "KeptLastAppointmentSpecify",
    "Reason Primary Appt Unmet": "",
    "Reason unscheduled": "",
    "Other healthcare provider": "",
    "Other MP": "",
    "Date Other MP": "",
    "Reason other MP": "",
    "Specialists": {
        "type":"question-array",
        "inputs": [
            {
                "inp1":"SpecialistFirstName",
                "inp2":"SpecialistLastName",
                "inp3":"SpecialistField",
                "inp4":"SpecialistNextVisit",
                "inp5":"KeptLastSpecialistAppointment1"
            },
            {
                "inp1":"SpecialistFirstName2",
                "inp2":"SpecialistLastName2",
                "inp3":"SpecialistField2",
                "inp4":"Specialist2NextVisit",
                "inp5":"KeptLastSpecialistAppointment2"
            },
            {
                "inp1":"SpecialistFirstName3",
                "inp2":"SpecialistLastName3",
                "inp3":"SpecialistField3",
                "inp4":"Specialist3NextVisit",
                "inp5":""
            },
            {
                "inp1":"SpecialistFirstName4",
                "inp2":"SpecialistLastName4",
                "inp3":"SpecialistField4",
                "inp4":"Specialist4NextVisit",
                "inp5":""
            },
            {
                "inp1":"SpecialistFirstName5",
                "inp2":"SpecialistLastName5",
                "inp3":"SpecialistField5",
                "inp4":"Specialist5NextVisit",
                "inp5":""
            }
        ]
    },
    "Specialist Name": "----",
    "Specialist Appointments": "",
    "Specify Missed Spec. Appt.": "",
    "Therapist": {
        "if":"Therapy",
        "then":"Yes",
        "else":"No"
    },
    "Therapist's Name": "----",
    "Therapist First Name": "FirstNameOfTherapist",
    "Therapist Last Name": "LastNameOfTherapist",
    "Current Medical Conditions": "",
    "Specify Medical Conditions": "SpecifyCurrentMedicalConditions",
    "Therapist Appointments": {
        "type":"question-array",
        "inputs": [
            {
                "inp1":"DateOfTherapy",
                "inp2":"KeptLastTherapyAppointment",
                "inp3":""
            }
        ]
    },
    "Allergies": {
        "if":"Allergies",
        "then":"Yes",
        "else":"No"
    },
    "Diabetes": {
        "if":"Diabetes",
        "then":"Yes",
        "else":"No"
    },
    "Smoker (present)-Client": {
        "if":"SmokerClient",
        "then":"Yes",
        "else":"No"
    },
    "Smoker (present)-Household Members, Friends, etc.": {
        "if":"SmokerHousehold",
        "then":"Yes",
        "else":"No"
    },
    "Heart disease": {
        "if":"HeartDisease",
        "then":"Yes",
        "else":"No"
    },
    "HIV Positive": {
        "if":"HIVpositive",
        "then":"Yes",
        "else":"No"
    },
    "Hypertension": {
        "if":"Hypertension",
        "then":"Yes",
        "else":"No"
    },
    "Kidney disease": {
        "if":"KidneyDisease",
        "then":"Yes",
        "else":"No"
    },
    "Psychiatric history": {
        "if":"PsychiatricHistory",
        "then":"Yes",
        "else":"No"
    },
    "Seizure disorder": {
        "if":"SeizureDisorder",
        "then":"Yes",
        "else":"No"
    },
    "Cervical problems": {
        "if":"CervicalProblems",
        "then":"Yes",
        "else":"No"
    },
    "STD's": {
        "if":"STDs",
        "then":"Yes",
        "else":"No"
    },
    "Medical History - Other": {
        "if":"OtherHistory",
        "then":"Yes",
        "else":"No"
    },
    "Specify Other Medical History": "OtherHistorySpecify",
    "History of Abuse": {
        "if":"HistoryOfAbuse",
        "then":"Yes",
        "else":"No"
    },
    "Specify Abuse": "SpecifyHistoryOfAbuse",
    "Depression Assessment": {
        "type":"question-array",
        "inputs": [
            {
                "inp1":"DepressionScore1Date",
                "inp2":"DepressionScore1"
            },
            {
                "inp1":"DepressionScore2Date",
                "inp2":"DepressionScore2"
            },
            {
                "inp1":"DepressionScore3Date",
                "inp2":"DepressionScore3"
            },
            {
                "inp1":"DepressionScore4Date",
                "inp2":"DepressionScore4"
            },
            {
                "inp1":"DepressionScore5Date",
                "inp2":"DepressionScore5"
            },
            {
                "inp1":"DepressionScore6Date",
                "inp2":"DepressionScore6"
            },
            {
                "inp1":"DepressionScore7Date",
                "inp2":"DepressionScore7"
            },
            {
                "inp1":"DepressionScore8Date",
                "inp2":"DepressionScore8"
            },
            {
                "inp1":"DepressionScore9Date",
                "inp2":"DepressionScore9"
            },
            {
                "inp1":"DepressionScore10Date",
                "inp2":"DepressionScore10"
            }
        ]
    },
    "Score too high": "",
    "Depression Score Alert": "",
    "Reason": "",
    "Currently Pregnant": "PregnancySectionDoesNotApplytoFamily",
    "Due Date": "PregnancyDueDate",
    "Subsequent Pregnancy": "SubsequentProgramPregnancy",
    "Gestational Age": "GestionalAgeWeeks",
    "Trimester": "PregnancyTrimester",
    "Receiving Prenatal Care": "ReceivingPrenatalCare",
    "Gest. Week Prenatal Care Began": "GestationalWeekPrenatalCareBegan",
    "Previous Prenatal Care Visits": "",
    "Number Prenatal Care Visits": "NumberOfPrenatalCareVisits",
    "Adequate Prenatal Care": "CurrentlyReceivingAdequatePrenatalCare",
    "Satisfied With Prenatal Care": "PrenatalCareSatasfaction",
    "Not Satisfied with Prenatal Care Reason": "",
    "Pregnancy Wanted": "PregnancyWanted",
    "Previous Pregnancies": "",
    "Number of Pregnancies": "NumberOfPregnancies",
    "Number of Live Births": "NumberOfLiveBirths",
    "Number of Living Children": "NumberOfLivingChildren",
    "Last Delivery Date": "DateOfLastDelivery",
    "Had Previous Pregnancy Complications": "PreviousPregnancyComplications",
    "Induced Miscarriages": "",
    "Spontaneous Miscarriages": "NumberOfSpontaneousMiscarriages",
    "Fetal Deaths": "NumberOfFetalDeaths",
    "Neonatal Deaths": "NumberOfNeonatalDeaths",
    "Pre-term labors": "NumberOfIncididentsOfPretermLabor",
    "Pre-term Deliveries": "NumberOfPretermDeliveries",
    "Low Birth Weight Babies": "NumberOfLowBirthRateBabies",
    "Multi Gestations": "NumberOfMultiGestations",
    "C-sections": "NumberOfCsections",
    "Labor/Delivery Complications": "LaborComplications",
    "Health or Medical Concerns - Pregnancy": "PregnancyConcerns",
    "Concern Resolved": "",
    "Avg Weight Change - Previous Pregnancy": "",
    "Weight Change - Pregnancy (lbs)": "WeightGainedDuringPregnancy",
    "Reason for Weight Change": "",
    "Reason Explanation": "",
    "Participates in the Community": "ParticipationInCommunity",
    "Participates in the Community - Where": "ParticipationInCommunityWhere",
    "Community Club Detail": "",
    "Church Group Detail": "",
    "Volunteer Detail": "",
    "Volunteer Hours": "VolunteerHoursSinceLast",
    "Previous Total Hours": "TotalVolunteerHours - VolunteerHoursSinceLast",
    "New Total Hours": "TotalVolunteerHours",
    "Employment Skills - Attitude": "EmploymentSkills1",
    "1. Attitude - Q1": "employment_skills_1_1",
    "Prev - 1. Attitude - Q1": "",
    "1. Attitude - Q2": "employment_skills_1_2",
    "Prev - 1. Attitude - Q2": "",
    "1. Attitude - Q3": "employment_skills_1_3",
    "Prev - 1. Attitude - Q3": "",
    "1. Attitude - Q4": "employment_skills_1_4",
    "Prev - 1. Attitude - Q4": "",
    "1. Attitude - Q5": "employment_skills_1_5",
    "Prev - 1. Attitude - Q5": "",
    "1. Attitude - Total": "employment_skills_1_total",
    "Prev - 1. Attitude - Total": "",
    "Employment Skills - Responsibility": "EmploymentSkills2",
    "2. Responsibility - Q1": "employment_skills_2_1",
    "Prev - 2. Responsibility - Q1": "",
    "2. Responsibility - Q2": "employment_skills_2_2",
    "Prev - 2. Responsibility - Q2": "",
    "2. Responsibility - Q3": "employment_skills_2_3",
    "Prev - 2. Responsibility - Q3": "",
    "2. Responsibility - Q4": "employment_skills_2_4",
    "Prev - 2. Responsibility - Q4": "",
    "2. Responsibility - Q5": "employment_skills_2_5",
    "Prev - 2. Responsibility - Q5": "",
    "2. Responsibility - Total": "employment_skills_2_total",
    "Prev - 2. Responsibility - Total": "",
    "Employment Skills - Communication": "EmploymentSkills3",
    "3. Communication - Q1": "employment_skills_3_1",
    "Prev - 3. Communication - Q1": "",
    "3. Communication - Q2": "employment_skills_3_2",
    "Prev - 3. Communication - Q2": "",
    "3. Communication - Q3": "employment_skills_3_3",
    "Prev - 3. Communication - Q3": "",
    "3. Communication - Q4": "employment_skills_3_4",
    "Prev - 3. Communication - Q4": "",
    "3. Communication - Q5": "employment_skills_3_5",
    "Prev - 3. Communication - Q5": "",
    "3. Communication - Total": "employment_skills_3_total",
    "Prev - 3. Communication - Total": "",
    "Employment Skills - Problem Solving Skills": "EmploymentSkills4",
    "4. Problem Solving Skills - Q1": "employment_skills_4_1",
    "Prev - 4. Problem Solving Skills - Q1": "",
    "4. Problem Solving Skills - Q2": "employment_skills_4_2",
    "Prev - 4. Problem Solving Skills - Q2": "",
    "4. Problem Solving Skills - Q3": "employment_skills_4_3",
    "Prev - 4. Problem Solving Skills - Q3": "",
    "4. Problem Solving Skills - Q4": "employment_skills_4_4",
    "Prev - 4. Problem Solving Skills - Q4": "",
    "4. Problem Solving Skills - Q5": "employment_skills_4_5",
    "Prev - 4. Problem Solving Skills - Q5": "",
    "4. Problem Solving Skills - Total": "employment_skills_4_total",
    "Prev - 4. Problem Solving Skills - Total": "",
    "Employment Skills - Workplace Preperation Skills": "EmploymentSkills5",
    "5. Workplace Preparation Skills - Q1": "employment_skills_5_1",
    "Prev - 5. Workplace Preparation Skills - Q1": "",
    "5. Workplace Preparation Skills - Q2": "employment_skills_5_2",
    "Prev - 5. Workplace Preparation Skills - Q2": "",
    "5. Workplace Preparation Skills - Q3": "employment_skills_5_3",
    "Prev - 5. Workplace Preparation Skills - Q3": "",
    "5. Workplace Preparation Skills - Q4": "employment_skills_5_4",
    "Prev - 5. Workplace Preparation Skills - Q4": "",
    "5. Workplace Preparation Skills - Q5": "employment_skills_5_5",
    "Prev - 5. Workplace Preparation Skills - Q5": "",
    "5. Workplace Preparation Skills - Total": "employment_skills_5_total",
    "Prev - 5. Workplace Preparation Skills - Total": "",
    "Employment Skills Total": "employment_skills_total_total",
    "Prev - Employment Skills Total": "",
    "Schooling Status": "",
    "Current Schooling Level": "SchoolGrade",
    "Specify Other Schooling": "",
    "Education History": "",
    "Education Type": "",
    "Pre High School Completion Grade": "",
    "Where - High School": "HighSchoolWhere",
    "High School Diploma": "HighSchoolDiplomaGED",
    "Date of Diploma": "DiplomaDateRecieved",
    "Currently Enrolled": "",
    "Highest Grade ": "",
    "Attending GED Classes": "AttendingGEDClasses",
    "GED Classes Start": "GEDClassesDateStarted",
    "GED Classes Complete": "GEDDateCompleted",
    "College Completed": "",
    "Vocational School Name": "VocationalSchoolName",
    "Vocational School City": "VocationalSchoolCity",
    "Vocational School State": "VocationalSchoolState",
    "Field of Study": "VocationalFieldOfStudy",
    "Completed": "",
    "Date of Completion": "VocationalCompletionDate",
    "Expected Completion Date": "ExpectedDateOfVocationalCompletion",
    "Specify Cert/Liscense": "OtherCertsLicenses,OtherLicensesHeld",
    "Referral": "",
    "Date of Referral": "",
    "Referral Category": "",
    "Other Reason": "",
    "Referred To": "",
    "Utilized?": "ClientReferralUtilization",
    "Circle of Support": "",
    "Initial Default People of Support - Name": "",
    "Initial Default People of Support - Relationship": "",
    "Family Goal Plan": "FamilyGoalPlan",
    "Issue - Family Goal Plan": "",
    "Strengths to build on": "",
    "Issue Resolved": "",
    "Date Resolved": "",
    "Mini Goals": "",
    "Mini Goal Date": "",
    "Mini Goal": "",
    "Means to complete": "",
    "Date to Complete": "",
    "Date Completed": "",
    "Outcome/Comments": "",
    "spacer": "",
    "spacer2": "",
    "Child Development Info": "",
    "CD Information Subject/Topic": "",
    "CD Information Source": "",
    "Module": "",
    "Improved Knowledge": "",
    "Improved CD Knowledge Description": "",
    "Cues": "",
    "Cues Observations": "",
    "Cues Frequency": "",
    "Cues Strategies": "",
    "Cues Strategies Used": "",
    "Cues Other Strategies - Other": "",
    "Cues Notes Specify": "",
    "Holding": "",
    "Holding Observations": "",
    "Holding Frequency": "",
    "Holding Strategies": "",
    "Holding Strategies Used": "",
    "Holding Other Strategies Specify": "",
    "Holding Notes Specify": "",
    "Expression": "",
    "Expression Observations": "",
    "Expression Frequency": "",
    "Expression Strategies": "",
    "Expression Strategies Used": "",
    "Other Expression Strategies Specify": "",
    "Expression Notes Specify": "",
    "Empathy": "",
    "Empathy Observations": "",
    "Empathy Frequency": "",
    "Empathy Strategies": "",
    "Empathy Strategies Used": "",
    "Empathy Other Strategies Specify": "",
    "Empathy Notes Specify": "",
    "Rhythmicity/Reciprosity": "",
    "Rhythmicity/Reciprosity Observations": "",
    "Rhythmicity/Reciprosity Frequency": "",
    "Rhythmicity/Reciprosity Strategies": "",
    "Rhythmicity/Reciprosity Strategies Used": "",
    "Rhythmicity/Reciprosity Other Strategies Specify": "",
    "Rhythmicity/Reciprosity Notes Specify": "",
    "Smiles": "",
    "Smiles Observations": "",
    "Smiles Frequency": "",
    "Smiles Strategies": "",
    "Smiles Strategies Used": "",
    "Smiles Other Strategies Specify": "",
    "Smiles Notes Specify": "",
    "Additonal Comments": "",
    "Actions During this Visit": "",
    "Information/Handouts Provided": "",
    "Incentive(s) Given": "",
    "Incentive Points Redeemed": "",
    "Books Given": "",
    "Plan for Next Visit": "",
    "Topic": "",
    "Planned Method": "",
    "Goal for Next Visit": "",
    "Next Visit Date": "",
    "Next Visit Time": "",
    "Reviewed Summary": "",
    "Client Name": "",
    "Client Number": "",
    "Sp-Visit Date": "",
    "Sp-Start Time": "",
    "Sp-End Time": "",
    "Sp-Visit Duration": "",
    "SP-HFA Level": "",
    "SP-HFA Points": "",
    "Sp-Present as Visit": "",
    "SP-Curriculum": "",
    "Sp-Module": ""
}`);
