exports.childVisitKeys = JSON.parse(`{
    "Previous Visit Date": "LastVisitDate",
    "Initial Visit Date": "InitialVisitDate",
    "Correct": "",
    "Visit Date": "VisitDate",
    "Visit Time": "",
    "Visit Time Start": "StartTime",
    "Visit Time End": "EndTime",
    "Visit Duration": "",
    "Previous Client": "PreviousClient",
    "Client Type": "ClientType",
    "Funding Level": "ClientLevel",
    "Other Funding Level": "",
    "DOB": "DateOfBirth",
    "Age": "ageyears",
    "Gender Identity": "Gender",
    "Other ": "",
    "Lives With": "ChildLivesWithName",
    "Lives With Else - 6": "",
    "Relationship - 6": "",
    "Lives With Else - 5": "",
    "Lives With Else - 4": "",
    "Lives With Else - 3": "",
    "Lives With Else - 2": "",
    "Lives With Else - 1": "",
    "Birth Weight": "",
    "Birth Weight Lb": "InfantWeightLbs",
    "BirthWeightOz": "InfantWeightOz",
    "Current Height": "",
    "Cur Height (ft)": "HeightFeet",
    "Cur Height (in)": "HeightInches",
    "Previous Height": "",
    "Prev Height (ft)": "",
    "Prev Height (in)": "",
    "Height Change": "HeightChange",
    "Current Weight": "",
    "Cur Weight (lb)": "CurrentWeightIbs",
    "Cur Weight (oz)": "CurrentWeightOz",
    "Previous Weight": "",
    "Prev Weight (lb)": "",
    "Prev Weight (oz)": "",
    "Weight Change": "WeightChangeLbs",
    "BMI": "",
    "Cur BMI": "BMI",
    "Prev BMI": "",
    "Change BMI": "BMIChange",
    "County": "County",
    "Other Specify": "",
    "Race": "Race",
    "MultipleRaces": "",
    "Other Race (Multi)": "",
    "Other Race (Single)": "",
    "Insurance": "Insurance",
    "Medicaid Number": "MedicaidNumber",
    "Status": "MedicaidPending||MedicaidInactive",
    "Other Insurance": "",
    "Other Insurance Status": "",
    "Medical Provider Name": "",
    "Medical Provider First Name": "DoctorsFirstName",
    "Medical Provider Last Name": "DoctorsLastName",
    "Type of Provider": "HealthCareProviderType",
    "Other Medical Provider": "",
    "Medical Conditions": "",
    "Condition Info": "",
    "Default Condition": "",
    "Default Diagnosed": "",
    "Default Resolved": "",
    "Medical Visits Primary": "",
    "PMP Appointment Date": "",
    "Kept PMP Visit": "keptlastappointment",
    "Specify Why Missed": "keptlastappointmentspecify",
    "Other healthcare provider": "",
    "Other MP": "",
    "Appointment Other MP": "",
    "Specify Other Visit": "",
    "Emergency Room": "",
    "Date of ER Visit": "ChildTreatedEmergencyRoomDate",
    "Reason For ER": "ERReason",
    "Safety Problem": "ERReasonOtherSafety",
    "Injury": "ERReasonOtherInjury",
    "Specify ER Reason": "",
    "ER Cause Prevent.": "ERVisitPreventable",
    "Specify Preventable Reason": "",
    "Specialists": "",
    "Specialist Name": "",
    "Specialist FName": "SpecialistFirstName",
    "Specialist LName": "SpecialistLastName,SpecialistLastName2,SpecialistLastName3,SpecialistLastName4,SpecialistLastName5",
    "Specialty": "Specialty",
    "Specialist Appointments": "",
    "Specialist App. Date": "SpecialistNextVisit,Specialist2NextVisit,Specialist3NextVisit,Specialist4NextVisit,Specialist5NextVisit",
    "Kept Specialist Appointment": "",
    "Specify Missed Spec. Appt.": "",
    "Breastfeeding": "Breastfeeding",
    "Weeks Breast Feeding": "NumberOfWeeksBreastfeeding",
    "Low Birth Weight": "LowBirthWeight",
    "Pre-term Delivery": "PretermDelivery",
    "Problems at Delivery": "ProblemAtDelivery",
    "Specify Deliv. Problems": "ProblemAtDeliverySpecify",
    "History of Abuse": "HistoryOfAbuse",
    "Specify Abuse": "SpecifyHistoryOfAbuse",
    "Immunizations Current": "ImmunizationsCurrent",
    "Verified Immun. Record": "VerifiedImmunizationRecord",
    "UTD Per Parent Report": "UTDPPR",
    "Specify": "UTDPPRComment",
    "Appropriate MP": "UsedAppropriateMDforChildsNeeds",
    "Same Medical Group": "UsedSameMDforAllHealthIssues",
    "Comfortable Exchanging Health Info": "FeelsComfortableExchangingHealthInfoWithMD",
    "Can Access MP": "CanAccessMDandServicesWhenNeeded",
    "Notifies MP": "NotifiesPrimaryMDofAnyOtherHealthServicesChildIsReceiving",
    "Medical Home": "MedicalHome",
    "Attends School": "",
    "School Name": "School",
    "School Type": "",
    "Name Other School Type": "",
    "Days in School": "",
    "Identified Behavioral Concerns": "IdentifiedLearningBehavioralConcernsAtSchool",
    "Specify Behavioral Concerns": "IdentifiedLearningBehavioralConcernsAtSchoolSpecify",
    "Current Age - ASQ": "asqage",
    "ASQ Questionnaire": "",
    "ASQ Questionnaire Type": "",
    "ASQ Questionnaire Date": "",
    "ASQ Communication": "",
    "Score (Communication)": "",
    "N/E (Communication)": "",
    "ASQ Gross Motor": "",
    "Score (Gross Motor)": "",
    "N/E (Gross Motor)": "",
    "ASQ Fine Motor": "",
    "Score (Fine Motor)": "",
    "N/E (Fine Motor)": "",
    "ASQ Problem Solving": "",
    "Score (Problem Solving)": "",
    "N/E (Problem Solving)": "",
    "ASQ Personal Social": "",
    "Score (Personal Social)": "",
    "N/E (Personal Social)": "",
    "Current Age - ASQ-SE": "",
    "ASQ-SE Questionnaire": "",
    "ASQ-SE Questionnaire Type": "",
    "ASQ-SE Score": "",
    "ASQ-SE Date": "",
    "Visit Summary": "visitsummary",
    "Reviewed W/ Client": "visitsummaryreviewed"
}`);
